export enum NotificationCategory {
  DPR_REMINDER = "DPR_REMINDER",
  DPR_ESCALATION = "DPR_ESCALATION",
  DPR_REVIEW = "DPR_REVIEW",
  LEAVE_APPROVAL = "LEAVE_APPROVAL",
  STALE_CANDIDATE = "STALE_CANDIDATE",
  GROUP_CHECK = "GROUP_CHECK",
  KRA = "KRA",
  STRIKE = "STRIKE",
  GENERAL = "GENERAL",
}
